### ISSUE TITLE
[WDLCompanion] Failed to set up WDL-only logging!

### ISSUE THREAD

**Issue by PsychoLynx** [Pokechu22/WorldDownloader-Serverside-Companion#1]
Using the latest 1.12-pre5

[16:01:53] [Server thread/INFO]: [WDLCompanion] Enabling WDLCompanion v1.1.2
[16:01:53] [Server thread/INFO]: [RemoteToolkitPlugin] Enabling RemoteToolkitPlugin vR10_A15.3
[16:01:53] [Server thread/INFO]: Error loading Toolkit plugin properties: java.io.FileNotFoundException: toolkit\remote.properties (Määritettyä polkua ei löydy)
[16:01:53] [Server thread/WARN]: java.io.FileNotFoundException: toolkit\remote.properties (Määritettyä polkua ei löydy)
[16:01:53] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[16:01:53] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[16:01:53] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[16:01:53] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[16:01:53] [Server thread/WARN]: 	at com.drdanick.McRKit.plugin.RTKPlugin.onEnable(RTKPlugin.java:50)
[16:01:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:01:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[16:01:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[16:01:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376)
[16:01:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326)
[16:01:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[16:01:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[16:01:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[16:01:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[16:01:53] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[16:01:53] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by dordsor21** [comment]
confirmed

**Comment by Pokechu22** [comment]
Ah, right, Mojang updated log4j, and my code that interacted with it broke.  Shouldn't be too hard to fix.

**Comment by Pokechu22** [comment]
That stacktrace isn't from my code (it's from another plugin); can you please get the correct stack trace?  In any case, it should be safe to ignore the message for now (separate log files won't be created, but those aren't vital to the plugin's function)

**Comment by dordsor21** [comment]
I didn't read through his reported error properly xD this is what I'm getting: https://hastebin.com/govonagivi.css

**Comment by Pokechu22** [comment]
As I expected.  Shouldn't be too hard to fix.

All this means is that WDL-specific logs won't be saved in its own folder; they'll only be located in the main server log file.  Which is fine.

You can stop the message by disabling the custom logging by setting `wdl.logMode` to `none` in the config.  I should be able to fix this soon, though (by 1.12's release, for sure).

**Comment by PsychoLynx** [comment]
Thank you kindly! ^^
