### ISSUE TITLE
console

### ISSUE THREAD

**Issue by Yukylyu** [Pokechu22/WorldDownloader-Serverside-Companion#3]
Hello i have this error :

[11:52:28] [Server thread/INFO]: [WDLCompanion] Enabling WDLCompanion v1.1.4
[11:52:28] [pool-11-thread-1/WARN]: Exception in thread "pool-11-thread-1" 
[11:52:28] [pool-11-thread-1/WARN]: java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_UNSIGNED 11025.0 Hz, 8 bit, stereo, 2 bytes/frame,  is supported.
[11:52:28] [pool-11-thread-1/WARN]: 	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:479)
[11:52:28] [pool-11-thread-1/WARN]: 	at me.decimix.notify.Core.PlaySound.play(PlaySound.java:76)
[11:52:28] [pool-11-thread-1/WARN]: 	at me.decimix.notify.Core.PlaySound.access$200(PlaySound.java:23)
[11:52:28] [pool-11-thread-1/WARN]: 	at me.decimix.notify.Core.PlaySound$1.run(PlaySound.java:43)
[11:52:28] [pool-11-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:52:28] [pool-11-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:52:28] [pool-11-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Pokechu22** [comment]
Not caused by this plugin.  WDLCompanion doesn't do anything with sounds.  Looking at that message, it seems to be coming from `me.decimix.notify` which I believe is [this plugin](https://dev.bukkit.org/projects/notify) (in fact I see a similar message in the comments).  That plugin appears to be intended to play sounds when you do something, and the error message seems to say there isn't any audio device available to play any sounds.
